// Auction - Generated by RustyPyCraw on 2026-04-03 14:05:28.231949
// Language: solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

contract Auction {
    struct AuctionData {
        address seller;
        uint256 startingBid;
        uint256 endTime;
        uint256 highestBid;
        address highestBidder;
        bool ended;
    }
    
    mapping(uint256 => AuctionData) public auctions;
    uint256 public auctionCount;
    
    event AuctionCreated(uint256 indexed id, address indexed seller, uint256 startingBid);
    event BidPlaced(uint256 indexed id, address indexed bidder, uint256 amount);
    
    function createAuction(uint256 startingBid, uint256 duration) external {
        auctionCount++;
        auctions[auctionCount] = AuctionData({
            seller: msg.sender,
            startingBid: startingBid,
            endTime: block.timestamp + duration,
            highestBid: 0,
            highestBidder: address(0),
            ended: false
        });
        
        emit AuctionCreated(auctionCount, msg.sender, startingBid);
    }
    
    function placeBid(uint256 auctionId) external payable {
        AuctionData storage auction = auctions[auctionId];
        require(block.timestamp < auction.endTime, "Auction ended");
        require(msg.value > auction.highestBid, "Bid too low");
        
        if (auction.highestBidder != address(0)) {
            payable(auction.highestBidder).transfer(auction.highestBid);
        }
        
        auction.highestBid = msg.value;
        auction.highestBidder = msg.sender;
        
        emit BidPlaced(auctionId, msg.sender, msg.value);
    }
}
