// auction_bot - Generated by RustyPyCraw on 2026-04-03 14:05:28.320815
// Language: javascript
// JavaScript/Node.js Blockchain Client
const { DirectSecp256k1HdWallet } = require('@cosmjs/proto-signing');
const { SigningStargateClient } = require('@cosmjs/stargate');

class TXClient {
    constructor(rpcUrl, mnemonic) {
        this.rpcUrl = rpcUrl;
        this.mnemonic = mnemonic;
        this.client = null;
        this.wallet = null;
    }
    
    async connect() {
        this.wallet = await DirectSecp256k1HdWallet.fromMnemonic(this.mnemonic, {
            prefix: "tx"
        });
        this.client = await SigningStargateClient.connectWithSigner(this.rpcUrl, this.wallet);
    }
    
    async placeBid(auctionId, amount) {
        const [account] = await this.wallet.getAccounts();
        
        const msg = {
            typeUrl: "/tx.MsgBid",
            value: {
                auctionId: auctionId,
                amount: amount.toString(),
                bidder: account.address
            }
        };
        
        const fee = {
            amount: [{ denom: "utestusd", amount: "5000" }],
            gas: "200000"
        };
        
        const result = await this.client.signAndBroadcast(
            account.address,
            [msg],
            fee
        );
        
        return result.transactionHash;
    }
}
