// AuctionKeeper - Generated by RustyPyCraw on 2026-04-03 14:05:28.171868
// Language: go
// Go Smart Contract (Cosmos SDK)
package keeper

import (
    "fmt"
    sdk "github.com/cosmos/cosmos-sdk/types"
    "github.com/tx/auction/x/auction/types"
)

func (k Keeper) CreateAuction(ctx sdk.Context, msg *types.MsgCreateAuction) error {
    auction := types.Auction{
        Id:          k.GetNextAuctionId(ctx),
        Seller:      msg.Seller,
        StartingBid: msg.StartingBid,
        EndTime:     ctx.BlockTime().Unix() + int64(msg.Duration),
        Collateral:  msg.Collateral,
    }
    
    k.SetAuction(ctx, auction)
    ctx.EventManager().EmitEvent(sdk.NewEvent(
        types.EventTypeCreateAuction,
        sdk.NewAttribute(types.AttributeKeyAuctionId, fmt.Sprintf("%d", auction.Id)),
        sdk.NewAttribute(types.AttributeKeySeller, auction.Seller),
    ))
    
    return nil
}
