// tx_client - Generated by RustyPyCraw on 2026-04-03 14:05:28.202656
// Language: python
# Python Web3 Interaction
from web3 import Web3
from eth_account import Account
import json

class TXBlockchain:
    def __init__(self, rpc_url: str, private_key: str):
        self.w3 = Web3(Web3.HTTPProvider(rpc_url))
        self.account = Account.from_key(private_key)
    
    def bid_on_auction(self, auction_id: int, amount: int):
        contract = self.w3.eth.contract(
            address=self.auction_address,
            abi=self.auction_abi
        )
        
        tx = contract.functions.placeBid(auction_id).build_transaction({
            'from': self.account.address,
            'value': amount,
            'gas': 200000,
            'gasPrice': self.w3.eth.gas_price
        })
        
        signed = self.account.sign_transaction(tx)
        tx_hash = self.w3.eth.send_raw_transaction(signed.rawTransaction)
        return tx_hash.hex()
