// TXClient - Generated by RustyPyCraw on 2026-04-03 14:05:28.292204
// Language: visual_basic
' Visual Basic .NET Blockchain Client
Imports System.Net.Http
Imports Newtonsoft.Json

Public Class TXClient
    Private ReadOnly _httpClient As HttpClient
    Private ReadOnly _rpcUrl As String
    
    Public Sub New(rpcUrl As String)
        _rpcUrl = rpcUrl
        _httpClient = New HttpClient()
    End Sub
    
    Public Async Function PlaceBidAsync(auctionId As Integer, amount As Long) As Task(Of String)
        Dim tx As New Dictionary(Of String, Object) From {
            {"msgs", New List(Of Object) From {
                New Dictionary(Of String, Object) From {
                    {"type", "/tx.MsgBid"},
                    {"value", New Dictionary(Of String, Object) From {
                        {"auction_id", auctionId},
                        {"amount", amount.ToString()}
                    }}
                }
            }}
        }
        
        Dim json = JsonConvert.SerializeObject(tx)
        Dim content = New StringContent(json, Encoding.UTF8, "application/json")
        
        Dim response = Await _httpClient.PostAsync($"{_rpcUrl}/tx", content)
        Return Await response.Content.ReadAsStringAsync()
    End Function
End Class
