"""
Code generation module for Rust/CosmWasm smart contracts
"""

import os
from datetime import datetime

class CodeGenerator:
    """Generate Rust/CosmWasm code from templates"""
    
    TEMPLATES = {
        "cosmwasm_contract": '''use cosmwasm_std::{
    entry_point, to_binary, Binary, Deps, DepsMut, Env, 
    MessageInfo, Response, StdResult, Addr, Uint128
};
use cw_storage_plus::Item;
use schemars::JsonSchema;
use serde::{Serialize, Deserialize};

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, JsonSchema)]
pub struct InstantiateMsg {{
    pub admin: String,
    pub token_denom: String,
}}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum ExecuteMsg {{
    Example {{ value: Uint128 }},
}}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum QueryMsg {{
    GetValue {{}},
}}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, JsonSchema)]
pub struct Config {{
    pub admin: Addr,
    pub token_denom: String,
}}

pub const CONFIG: Item<Config> = Item::new("config");

#[entry_point]
pub fn instantiate(
    deps: DepsMut,
    _env: Env,
    info: MessageInfo,
    msg: InstantiateMsg,
) -> StdResult<Response> {{
    let config = Config {{
        admin: deps.api.addr_validate(&msg.admin)?,
        token_denom: msg.token_denom,
    }};
    CONFIG.save(deps.storage, &config)?;
    
    Ok(Response::new()
        .add_attribute("method", "instantiate")
        .add_attribute("admin", config.admin))
}}

#[entry_point]
pub fn execute(
    deps: DepsMut,
    env: Env,
    info: MessageInfo,
    msg: ExecuteMsg,
) -> StdResult<Response> {{
    match msg {{
        ExecuteMsg::Example {{ value }} => execute_example(deps, env, info, value),
    }}
}}

fn execute_example(
    deps: DepsMut,
    _env: Env,
    info: MessageInfo,
    value: Uint128,
) -> StdResult<Response> {{
    Ok(Response::new()
        .add_attribute("action", "example")
        .add_attribute("sender", info.sender)
        .add_attribute("value", value))
}}

#[entry_point]
pub fn query(deps: Deps, _env: Env, msg: QueryMsg) -> StdResult<Binary> {{
    match msg {{
        QueryMsg::GetValue {{}} => to_binary(&"value"),
    }}
}}
''',
        
        "test_template": '''#[cfg(test)]
mod tests {{
    use super::*;
    use cosmwasm_std::testing::{{mock_dependencies, mock_env, mock_info}};

    #[test]
    fn proper_initialization() {{
        let mut deps = mock_dependencies();
        let msg = InstantiateMsg {{
            admin: "admin".to_string(),
            token_denom: "token".to_string(),
        }};
        let info = mock_info("creator", &[]);
        let res = instantiate(deps.as_mut(), mock_env(), info, msg).unwrap();
        assert_eq!(0, res.messages.len());
    }}
}}
''',
    }
    
    @classmethod
    def generate_contract(cls, name: str, features: list) -> str:
        """Generate a new CosmWasm contract"""
        contract = cls.TEMPLATES["cosmwasm_contract"]
        
        # Customize based on features
        if "cw20" in features:
            contract = contract.replace("Example", "Transfer")
        if "nft" in features:
            contract = contract.replace("Uint128", "String")
        
        return f"// {name} - Generated by RustyPyCraw on {datetime.now()}\n// Features: {', '.join(features)}\n\n{contract}"
    
    @classmethod
    def generate_tests(cls) -> str:
        """Generate test suite for a contract"""
        return cls.TEMPLATES["test_template"]
